# Generated by cucumber-sinatra. (Fri Feb 08 15:06:44 +1100 2013)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'app.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.default_driver = :selenium
Capybara.app = Sinatra::Application

class SearchWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  SearchWorld.new
end
